export const LOGIN_ADMIN = "account/admin/login"
export const LOGIN_CLIENT = "account/login"
export const ACCOUNT_HOTEL = "account/hotel"

export const ANALYTICS_LOG = "userlog/userlog"

export const PRODUCT_LIST = "product/list"
export const PRODUCT_MANAGE = "product/manage"
export const PRODUCT_TOGGLE = "product/toggle"
export const PRODUCT_CART_ENABLED = "product/cartenabled"
export const PRODUCT_CATEGORIES = "product/categories"
export const PRODUCT_ALLCATEGORIES = "product/allcategories"
export const PRODUCT_SEARCH = "product/search"
export const PRODUCT_FINDBYID = "product/findbyid"
export const PRODUCT_CREATE = "product/create"
export const PRODUCT_UPDATE = "product/update"
export const PRODUCT_DELETE = "product/delete"

export const ORDER_SAVE = "order/save"
export const ORDER_LIST = "order/list"
export const ORDER_NOTIFICATIONS_BYCLIENT = "order/notifbyclient"
export const ORDER_LIST_BYCLIENT = "order/listbyclient"
export const ORDER_FINDBYID = "order/findbyid"
export const ORDER_DETAIL = "order/detail"
export const ORDER_MARK_VIEWED = "order/markviewed"
export const ORDER_VALIDATE_BREAKFAST = "order/validatebreakfast"
export const ORDER_APPROVE = "order/approve"
export const ORDER_REJECT = "order/reject"
export const ORDER_FINALIZE = "order/finalize"
export const ORDER_REASONS = "order/reasons"
export const ORDER_DISCOUNT = "order/discount"

export const CART_CONFIG_LIST = "cartconfig/list"
export const CART_CONFIG_ADD = "cartconfig/add"
export const CART_CONFIG_EDIT = "cartconfig/edit"

export const INFO_DIRECTORY = "info/directory"
export const INFO_SLIDER = "info/slider"
export const INFO_BREAKFAST_SCHED = "info/schedule"
export const INFO_HOTELS = "info/hotels"
export const INFO_HOTELINFO = "info/hotelinfo"
export const INFO_PROVIDERS = "info/providers"
export const INFO_LATECHECK = "info/latecheckout"
export const INFO_PAYMENT_TYPES = "info/paymtypes"
export const INFO_HOTELCODE = "info/hotelcode"
export const INFO_CLEANING = "info/cleaning"

export const DIGITAL_LIST = "digitalmenu/list"

export const HOMEMENU_LIST = "homemenu/list"
export const HOMEMENU_LISTADMIN = "homemenu/listadmin"
export const HOMEMENU_CREATE = "homemenu/create"
export const HOMEMENU_EDIT = "homemenu/edit"

export const DIRECTORY_LIST = "directory/list"
export const DIRECTORY_LISTADMIN = "directory/listadmin"
export const DIRECTORY_UPSERTHEAD = "directory/upserthead"
export const DIRECTORY_CREATE = "directory/create"
export const DIRECTORY_EDIT = "directory/edit"

export const INTAKE_LIST = "intake/list"
export const INTAKE_DETAIL = "intake/detail"
export const INTAKE_MAIL = "intake/sendmail"
export const INTAKE_REASONS = "intake/reasons"
export const INTAKE_CANAGREE = "intake/canagree"

export const INFOPAGE_LIST = "infopage/list"
export const INFOPAGE_CREATE = "infopage/create"
export const INFOPAGE_EDIT = "infopage/edit"

export const INFOPAGE_DETAIL_LIST = "infopagedetail/list"
export const INFOPAGE_DETAIL_LISTADMIN = "infopagedetail/listadmin"
export const INFOPAGE_DETAIL_CREATE = "infopagedetail/create"
export const INFOPAGE_DETAIL_EDIT = "infopagedetail/edit"
